// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/Auth/service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_Auth_service_proto protoreflect.FileDescriptor

const file_proto_Auth_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/Auth/service.proto\x12\x04auth\x1a\x1aproto/Auth/type/user.proto\x1a\x1bgoogle/protobuf/empty.proto2\xab\x03\n" +
	"\vAuthService\x127\n" +
	"\fRegisterUser\x12\x19.auth.RegisterUserRequest\x1a\n" +
	".auth.User\"\x00\x12)\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\n" +
	".auth.User\"\x00\x12F\n" +
	"\x0eUpdateUserInfo\x12\x1b.auth.UpdateInfoUserRequest\x1a\x15.auth.BooleanResponse\"\x00\x12D\n" +
	"\fUploadAvatar\x12\x19.auth.UploadAvatarRequest\x1a\x15.auth.BooleanResponse\"\x00(\x01\x12'\n" +
	"\tFetchUser\x12\f.auth.SendID\x1a\n" +
	".auth.User\"\x00\x12F\n" +
	"\x0eChangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\x15.auth.BooleanResponse\"\x00\x129\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x15.auth.BooleanResponse\"\x00B:Z8github.com/Ilhamkawe/crowdfunding-proto/protogen/go/authb\x06proto3"

var file_proto_Auth_service_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),   // 0: auth.RegisterUserRequest
	(*LoginRequest)(nil),          // 1: auth.LoginRequest
	(*UpdateInfoUserRequest)(nil), // 2: auth.UpdateInfoUserRequest
	(*UploadAvatarRequest)(nil),   // 3: auth.UploadAvatarRequest
	(*SendID)(nil),                // 4: auth.SendID
	(*ChangePasswordRequest)(nil), // 5: auth.ChangePasswordRequest
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
	(*User)(nil),                  // 7: auth.User
	(*BooleanResponse)(nil),       // 8: auth.BooleanResponse
}
var file_proto_Auth_service_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.RegisterUser:input_type -> auth.RegisterUserRequest
	1, // 1: auth.AuthService.Login:input_type -> auth.LoginRequest
	2, // 2: auth.AuthService.UpdateUserInfo:input_type -> auth.UpdateInfoUserRequest
	3, // 3: auth.AuthService.UploadAvatar:input_type -> auth.UploadAvatarRequest
	4, // 4: auth.AuthService.FetchUser:input_type -> auth.SendID
	5, // 5: auth.AuthService.ChangePassword:input_type -> auth.ChangePasswordRequest
	6, // 6: auth.AuthService.Logout:input_type -> google.protobuf.Empty
	7, // 7: auth.AuthService.RegisterUser:output_type -> auth.User
	7, // 8: auth.AuthService.Login:output_type -> auth.User
	8, // 9: auth.AuthService.UpdateUserInfo:output_type -> auth.BooleanResponse
	8, // 10: auth.AuthService.UploadAvatar:output_type -> auth.BooleanResponse
	7, // 11: auth.AuthService.FetchUser:output_type -> auth.User
	8, // 12: auth.AuthService.ChangePassword:output_type -> auth.BooleanResponse
	8, // 13: auth.AuthService.Logout:output_type -> auth.BooleanResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Auth_service_proto_init() }
func file_proto_Auth_service_proto_init() {
	if File_proto_Auth_service_proto != nil {
		return
	}
	file_proto_Auth_type_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Auth_service_proto_rawDesc), len(file_proto_Auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Auth_service_proto_goTypes,
		DependencyIndexes: file_proto_Auth_service_proto_depIdxs,
	}.Build()
	File_proto_Auth_service_proto = out.File
	file_proto_Auth_service_proto_goTypes = nil
	file_proto_Auth_service_proto_depIdxs = nil
}
