// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/Campaign/type/campaign.proto

package campaign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Campaign struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BackerCount      int64                  `protobuf:"varint,6,opt,name=backerCount,proto3" json:"backerCount,omitempty"`
	GoalAmount       int64                  `protobuf:"varint,7,opt,name=goalAmount,proto3" json:"goalAmount,omitempty"`
	Cattegory        string                 `protobuf:"bytes,8,opt,name=cattegory,proto3" json:"cattegory,omitempty"`
	CurrentAmount    int64                  `protobuf:"varint,9,opt,name=currentAmount,proto3" json:"currentAmount,omitempty"`
	Slug             string                 `protobuf:"bytes,10,opt,name=slug,proto3" json:"slug,omitempty"`
	Status           string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Attachment       string                 `protobuf:"bytes,12,opt,name=Attachment,proto3" json:"Attachment,omitempty"`
	CollectAble      bool                   `protobuf:"varint,13,opt,name=collectAble,proto3" json:"collectAble,omitempty"`
	FinishAt         string                 `protobuf:"bytes,15,opt,name=finishAt,proto3" json:"finishAt,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Campaign) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetBackerCount() int64 {
	if x != nil {
		return x.BackerCount
	}
	return 0
}

func (x *Campaign) GetGoalAmount() int64 {
	if x != nil {
		return x.GoalAmount
	}
	return 0
}

func (x *Campaign) GetCattegory() string {
	if x != nil {
		return x.Cattegory
	}
	return ""
}

func (x *Campaign) GetCurrentAmount() int64 {
	if x != nil {
		return x.CurrentAmount
	}
	return 0
}

func (x *Campaign) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *Campaign) GetCollectAble() bool {
	if x != nil {
		return x.CollectAble
	}
	return false
}

func (x *Campaign) GetFinishAt() string {
	if x != nil {
		return x.FinishAt
	}
	return ""
}

func (x *Campaign) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Campaign) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListCampaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Campaign            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaign) Reset() {
	*x = ListCampaign{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaign) ProtoMessage() {}

func (x *ListCampaign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaign.ProtoReflect.Descriptor instead.
func (*ListCampaign) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *ListCampaign) GetData() []*Campaign {
	if x != nil {
		return x.Data
	}
	return nil
}

type CampaignImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignID    int64                  `protobuf:"varint,2,opt,name=campaignID,proto3" json:"campaignID,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	IsPrimary     int32                  `protobuf:"varint,4,opt,name=isPrimary,proto3" json:"isPrimary,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignImage) Reset() {
	*x = CampaignImage{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignImage) ProtoMessage() {}

func (x *CampaignImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignImage.ProtoReflect.Descriptor instead.
func (*CampaignImage) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *CampaignImage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CampaignImage) GetCampaignID() int64 {
	if x != nil {
		return x.CampaignID
	}
	return 0
}

func (x *CampaignImage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CampaignImage) GetIsPrimary() int32 {
	if x != nil {
		return x.IsPrimary
	}
	return 0
}

func (x *CampaignImage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CampaignImage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CampaignReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,2,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Perks         string                 `protobuf:"bytes,4,opt,name=perks,proto3" json:"perks,omitempty"`
	MinDonate     int32                  `protobuf:"varint,5,opt,name=minDonate,proto3" json:"minDonate,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignReward) Reset() {
	*x = CampaignReward{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignReward) ProtoMessage() {}

func (x *CampaignReward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignReward.ProtoReflect.Descriptor instead.
func (*CampaignReward) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{3}
}

func (x *CampaignReward) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CampaignReward) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CampaignReward) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CampaignReward) GetPerks() string {
	if x != nil {
		return x.Perks
	}
	return ""
}

func (x *CampaignReward) GetMinDonate() int32 {
	if x != nil {
		return x.MinDonate
	}
	return 0
}

func (x *CampaignReward) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CampaignReward) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CampaignActivity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId       int32                  `protobuf:"varint,2,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Slug             string                 `protobuf:"bytes,7,opt,name=slug,proto3" json:"slug,omitempty"`
	Campaign         *Campaign              `protobuf:"bytes,8,opt,name=campaign,proto3" json:"campaign,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CampaignActivity) Reset() {
	*x = CampaignActivity{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignActivity) ProtoMessage() {}

func (x *CampaignActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignActivity.ProtoReflect.Descriptor instead.
func (*CampaignActivity) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{4}
}

func (x *CampaignActivity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CampaignActivity) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CampaignActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CampaignActivity) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CampaignActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CampaignActivity) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CampaignActivity) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CampaignActivity) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

func (x *CampaignActivity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CampaignActivity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Cattegory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cattegory) Reset() {
	*x = Cattegory{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cattegory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cattegory) ProtoMessage() {}

func (x *Cattegory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cattegory.ProtoReflect.Descriptor instead.
func (*Cattegory) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{5}
}

func (x *Cattegory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cattegory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCattegory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Cattegory           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCattegory) Reset() {
	*x = ListCattegory{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCattegory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCattegory) ProtoMessage() {}

func (x *ListCattegory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCattegory.ProtoReflect.Descriptor instead.
func (*ListCattegory) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{6}
}

func (x *ListCattegory) GetData() []*Cattegory {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendIDRequest) Reset() {
	*x = SendIDRequest{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIDRequest) ProtoMessage() {}

func (x *SendIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIDRequest.ProtoReflect.Descriptor instead.
func (*SendIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{7}
}

func (x *SendIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SendLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLimitRequest) Reset() {
	*x = SendLimitRequest{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLimitRequest) ProtoMessage() {}

func (x *SendLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLimitRequest.ProtoReflect.Descriptor instead.
func (*SendLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{8}
}

func (x *SendLimitRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SendUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserIDRequest) Reset() {
	*x = SendUserIDRequest{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserIDRequest) ProtoMessage() {}

func (x *SendUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserIDRequest.ProtoReflect.Descriptor instead.
func (*SendUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{9}
}

func (x *SendUserIDRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateCampaignInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ShortDescription string                 `protobuf:"bytes,2,opt,name=ShortDescription,proto3" json:"ShortDescription,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	GoalAmount       string                 `protobuf:"bytes,4,opt,name=GoalAmount,proto3" json:"GoalAmount,omitempty"`
	Cattegory        string                 `protobuf:"bytes,5,opt,name=Cattegory,proto3" json:"Cattegory,omitempty"`
	FinishAt         string                 `protobuf:"bytes,6,opt,name=FinishAt,proto3" json:"FinishAt,omitempty"`
	Path             string                 `protobuf:"bytes,7,opt,name=Path,proto3" json:"Path,omitempty"`
	UserId           int32                  `protobuf:"varint,8,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCampaignInput) Reset() {
	*x = CreateCampaignInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignInput) ProtoMessage() {}

func (x *CreateCampaignInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignInput.ProtoReflect.Descriptor instead.
func (*CreateCampaignInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCampaignInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignInput) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateCampaignInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignInput) GetGoalAmount() string {
	if x != nil {
		return x.GoalAmount
	}
	return ""
}

func (x *CreateCampaignInput) GetCattegory() string {
	if x != nil {
		return x.Cattegory
	}
	return ""
}

func (x *CreateCampaignInput) GetFinishAt() string {
	if x != nil {
		return x.FinishAt
	}
	return ""
}

func (x *CreateCampaignInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateCampaignInput) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateAttachmentInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignID    string                 `protobuf:"bytes,1,opt,name=CampaignID,proto3" json:"CampaignID,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttachmentInput) Reset() {
	*x = UpdateAttachmentInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttachmentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttachmentInput) ProtoMessage() {}

func (x *UpdateAttachmentInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttachmentInput.ProtoReflect.Descriptor instead.
func (*UpdateAttachmentInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAttachmentInput) GetCampaignID() string {
	if x != nil {
		return x.CampaignID
	}
	return ""
}

func (x *UpdateAttachmentInput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateAttachmentInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateAttachmentInput) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateCampaignInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ShortDescription string                 `protobuf:"bytes,3,opt,name=ShortDescription,proto3" json:"ShortDescription,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	GoalAmount       string                 `protobuf:"bytes,5,opt,name=GoalAmount,proto3" json:"GoalAmount,omitempty"`
	Cattegory        string                 `protobuf:"bytes,6,opt,name=Cattegory,proto3" json:"Cattegory,omitempty"`
	UserId           string                 `protobuf:"bytes,7,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateCampaignInput) Reset() {
	*x = UpdateCampaignInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignInput) ProtoMessage() {}

func (x *UpdateCampaignInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignInput.ProtoReflect.Descriptor instead.
func (*UpdateCampaignInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCampaignInput) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCampaignInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignInput) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *UpdateCampaignInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCampaignInput) GetGoalAmount() string {
	if x != nil {
		return x.GoalAmount
	}
	return ""
}

func (x *UpdateCampaignInput) GetCattegory() string {
	if x != nil {
		return x.Cattegory
	}
	return ""
}

func (x *UpdateCampaignInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateCampaignImageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,2,opt,name=IsPrimary,proto3" json:"IsPrimary,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignImageInput) Reset() {
	*x = CreateCampaignImageInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignImageInput) ProtoMessage() {}

func (x *CreateCampaignImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignImageInput.ProtoReflect.Descriptor instead.
func (*CreateCampaignImageInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCampaignImageInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CreateCampaignImageInput) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreateCampaignImageInput) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCampaignImageInput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type CreateCampaignRewardInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Perks         string                 `protobuf:"bytes,3,opt,name=Perks,proto3" json:"Perks,omitempty"`
	MinDonate     string                 `protobuf:"bytes,4,opt,name=MinDonate,proto3" json:"MinDonate,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRewardInput) Reset() {
	*x = CreateCampaignRewardInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRewardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRewardInput) ProtoMessage() {}

func (x *CreateCampaignRewardInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRewardInput.ProtoReflect.Descriptor instead.
func (*CreateCampaignRewardInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCampaignRewardInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CreateCampaignRewardInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRewardInput) GetPerks() string {
	if x != nil {
		return x.Perks
	}
	return ""
}

func (x *CreateCampaignRewardInput) GetMinDonate() string {
	if x != nil {
		return x.MinDonate
	}
	return ""
}

func (x *CreateCampaignRewardInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCampaignRewardInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	RewardId      int32                  `protobuf:"varint,2,opt,name=RewardId,proto3" json:"RewardId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRewardInput) Reset() {
	*x = DeleteCampaignRewardInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRewardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRewardInput) ProtoMessage() {}

func (x *DeleteCampaignRewardInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRewardInput.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRewardInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCampaignRewardInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DeleteCampaignRewardInput) GetRewardId() int32 {
	if x != nil {
		return x.RewardId
	}
	return 0
}

func (x *DeleteCampaignRewardInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCampaignImageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	ImageId       int32                  `protobuf:"varint,2,opt,name=ImageId,proto3" json:"ImageId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignImageInput) Reset() {
	*x = DeleteCampaignImageInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignImageInput) ProtoMessage() {}

func (x *DeleteCampaignImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignImageInput.ProtoReflect.Descriptor instead.
func (*DeleteCampaignImageInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCampaignImageInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DeleteCampaignImageInput) GetImageId() int32 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *DeleteCampaignImageInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BooleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanResponse) Reset() {
	*x = BooleanResponse{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanResponse) ProtoMessage() {}

func (x *BooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanResponse.ProtoReflect.Descriptor instead.
func (*BooleanResponse) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{17}
}

func (x *BooleanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BooleanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateCampaignActivityInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CampaignId       int32                  `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ShortDescription string                 `protobuf:"bytes,3,opt,name=ShortDescription,proto3" json:"ShortDescription,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,5,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	Chunk            []byte                 `protobuf:"bytes,6,opt,name=chunk,proto3" json:"chunk,omitempty"`
	UserId           string                 `protobuf:"bytes,7,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCampaignActivityInput) Reset() {
	*x = CreateCampaignActivityInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignActivityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignActivityInput) ProtoMessage() {}

func (x *CreateCampaignActivityInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignActivityInput.ProtoReflect.Descriptor instead.
func (*CreateCampaignActivityInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCampaignActivityInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CreateCampaignActivityInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignActivityInput) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateCampaignActivityInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignActivityInput) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateCampaignActivityInput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *CreateCampaignActivityInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateCampaignActivityInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CampaignId       int32                  `protobuf:"varint,2,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=ShortDescription,proto3" json:"ShortDescription,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,6,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	Chunk            []byte                 `protobuf:"bytes,7,opt,name=chunk,proto3" json:"chunk,omitempty"`
	UserId           string                 `protobuf:"bytes,8,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateCampaignActivityInput) Reset() {
	*x = UpdateCampaignActivityInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignActivityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignActivityInput) ProtoMessage() {}

func (x *UpdateCampaignActivityInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignActivityInput.ProtoReflect.Descriptor instead.
func (*UpdateCampaignActivityInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCampaignActivityInput) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCampaignActivityInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *UpdateCampaignActivityInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignActivityInput) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *UpdateCampaignActivityInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCampaignActivityInput) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateCampaignActivityInput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *UpdateCampaignActivityInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCampaignActivityInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	ActivityId    int32                  `protobuf:"varint,2,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignActivityInput) Reset() {
	*x = DeleteCampaignActivityInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignActivityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignActivityInput) ProtoMessage() {}

func (x *DeleteCampaignActivityInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignActivityInput.ProtoReflect.Descriptor instead.
func (*DeleteCampaignActivityInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCampaignActivityInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *DeleteCampaignActivityInput) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *DeleteCampaignActivityInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCampaignAcitityInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,2,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignAcitityInput) Reset() {
	*x = GetCampaignAcitityInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignAcitityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignAcitityInput) ProtoMessage() {}

func (x *GetCampaignAcitityInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignAcitityInput.ProtoReflect.Descriptor instead.
func (*GetCampaignAcitityInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{21}
}

func (x *GetCampaignAcitityInput) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCampaignAcitityInput) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type SendCattegoryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCattegoryInput) Reset() {
	*x = SendCattegoryInput{}
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCattegoryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCattegoryInput) ProtoMessage() {}

func (x *SendCattegoryInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Campaign_type_campaign_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCattegoryInput.ProtoReflect.Descriptor instead.
func (*SendCattegoryInput) Descriptor() ([]byte, []int) {
	return file_proto_Campaign_type_campaign_proto_rawDescGZIP(), []int{22}
}

func (x *SendCattegoryInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_Campaign_type_campaign_proto protoreflect.FileDescriptor

const file_proto_Campaign_type_campaign_proto_rawDesc = "" +
	"\n" +
	"\"proto/Campaign/type/campaign.proto\x12\bcampaign\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x03\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\x10shortDescription\x18\x04 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12 \n" +
	"\vbackerCount\x18\x06 \x01(\x03R\vbackerCount\x12\x1e\n" +
	"\n" +
	"goalAmount\x18\a \x01(\x03R\n" +
	"goalAmount\x12\x1c\n" +
	"\tcattegory\x18\b \x01(\tR\tcattegory\x12$\n" +
	"\rcurrentAmount\x18\t \x01(\x03R\rcurrentAmount\x12\x12\n" +
	"\x04slug\x18\n" +
	" \x01(\tR\x04slug\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"Attachment\x18\f \x01(\tR\n" +
	"Attachment\x12 \n" +
	"\vcollectAble\x18\r \x01(\bR\vcollectAble\x12\x1a\n" +
	"\bfinishAt\x18\x0f \x01(\tR\bfinishAt\x12\x1c\n" +
	"\tcreatedAt\x18\x10 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x11 \x01(\tR\tupdatedAt\"6\n" +
	"\fListCampaign\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.campaign.CampaignR\x04data\"\xb5\x01\n" +
	"\rCampaignImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"campaignID\x18\x02 \x01(\x03R\n" +
	"campaignID\x12\x1a\n" +
	"\bfileName\x18\x03 \x01(\tR\bfileName\x12\x1c\n" +
	"\tisPrimary\x18\x04 \x01(\x05R\tisPrimary\x12\x1c\n" +
	"\tcreatedAt\x18\x10 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x11 \x01(\tR\tupdatedAt\"\x8a\x02\n" +
	"\x0eCampaignReward\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"campaignId\x18\x02 \x01(\x05R\n" +
	"campaignId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05perks\x18\x04 \x01(\tR\x05perks\x12\x1c\n" +
	"\tminDonate\x18\x05 \x01(\x05R\tminDonate\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf8\x02\n" +
	"\x10CampaignActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"campaignId\x18\x02 \x01(\x05R\n" +
	"campaignId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\x10shortDescription\x18\x04 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bimageUrl\x18\x06 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04slug\x18\a \x01(\tR\x04slug\x12.\n" +
	"\bcampaign\x18\b \x01(\v2\x12.campaign.CampaignR\bcampaign\x128\n" +
	"\tcreatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\tCattegory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"8\n" +
	"\rListCattegory\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.campaign.CattegoryR\x04data\"\x1f\n" +
	"\rSendIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"(\n" +
	"\x10SendLimitRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"+\n" +
	"\x11SendUserIDRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"\xfd\x01\n" +
	"\x13CreateCampaignInput\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12*\n" +
	"\x10ShortDescription\x18\x02 \x01(\tR\x10ShortDescription\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"GoalAmount\x18\x04 \x01(\tR\n" +
	"GoalAmount\x12\x1c\n" +
	"\tCattegory\x18\x05 \x01(\tR\tCattegory\x12\x1a\n" +
	"\bFinishAt\x18\x06 \x01(\tR\bFinishAt\x12\x12\n" +
	"\x04Path\x18\a \x01(\tR\x04Path\x12\x16\n" +
	"\x06UserId\x18\b \x01(\x05R\x06UserId\"{\n" +
	"\x15UpdateAttachmentInput\x12\x1e\n" +
	"\n" +
	"CampaignID\x18\x01 \x01(\tR\n" +
	"CampaignID\x12\x16\n" +
	"\x06Action\x18\x02 \x01(\tR\x06Action\x12\x12\n" +
	"\x04Path\x18\x03 \x01(\tR\x04Path\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x05R\x06UserId\"\xdd\x01\n" +
	"\x13UpdateCampaignInput\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12*\n" +
	"\x10ShortDescription\x18\x03 \x01(\tR\x10ShortDescription\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"GoalAmount\x18\x05 \x01(\tR\n" +
	"GoalAmount\x12\x1c\n" +
	"\tCattegory\x18\x06 \x01(\tR\tCattegory\x12\x16\n" +
	"\x06UserId\x18\a \x01(\tR\x06UserId\"\x86\x01\n" +
	"\x18CreateCampaignImageInput\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x01 \x01(\x05R\n" +
	"CampaignId\x12\x1c\n" +
	"\tIsPrimary\x18\x02 \x01(\bR\tIsPrimary\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\x05R\x06UserId\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\"\xa9\x01\n" +
	"\x19CreateCampaignRewardInput\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x01 \x01(\x05R\n" +
	"CampaignId\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Perks\x18\x03 \x01(\tR\x05Perks\x12\x1c\n" +
	"\tMinDonate\x18\x04 \x01(\tR\tMinDonate\x12\x16\n" +
	"\x06UserId\x18\x05 \x01(\tR\x06UserId\"o\n" +
	"\x19DeleteCampaignRewardInput\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x01 \x01(\x05R\n" +
	"CampaignId\x12\x1a\n" +
	"\bRewardId\x18\x02 \x01(\x05R\bRewardId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\tR\x06UserId\"l\n" +
	"\x18DeleteCampaignImageInput\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x01 \x01(\x05R\n" +
	"CampaignId\x12\x18\n" +
	"\aImageId\x18\x02 \x01(\x05R\aImageId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\tR\x06UserId\"E\n" +
	"\x0fBooleanResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xe9\x01\n" +
	"\x1bCreateCampaignActivityInput\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x01 \x01(\x05R\n" +
	"CampaignId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12*\n" +
	"\x10ShortDescription\x18\x03 \x01(\tR\x10ShortDescription\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x1a\n" +
	"\bImageUrl\x18\x05 \x01(\tR\bImageUrl\x12\x14\n" +
	"\x05chunk\x18\x06 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06UserId\x18\a \x01(\tR\x06UserId\"\xf9\x01\n" +
	"\x1bUpdateCampaignActivityInput\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x02 \x01(\x05R\n" +
	"CampaignId\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12*\n" +
	"\x10ShortDescription\x18\x04 \x01(\tR\x10ShortDescription\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x1a\n" +
	"\bImageUrl\x18\x06 \x01(\tR\bImageUrl\x12\x14\n" +
	"\x05chunk\x18\a \x01(\fR\x05chunk\x12\x16\n" +
	"\x06UserId\x18\b \x01(\tR\x06UserId\"u\n" +
	"\x1bDeleteCampaignActivityInput\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x01 \x01(\x05R\n" +
	"CampaignId\x12\x1e\n" +
	"\n" +
	"ActivityId\x18\x02 \x01(\x05R\n" +
	"ActivityId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\tR\x06UserId\"I\n" +
	"\x17GetCampaignAcitityInput\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1e\n" +
	"\n" +
	"CampaignId\x18\x02 \x01(\x05R\n" +
	"CampaignId\"(\n" +
	"\x12SendCattegoryInput\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04NameB>Z<github.com/Ilhamkawe/crowdfunding-proto/protogen/go/campaignb\x06proto3"

var (
	file_proto_Campaign_type_campaign_proto_rawDescOnce sync.Once
	file_proto_Campaign_type_campaign_proto_rawDescData []byte
)

func file_proto_Campaign_type_campaign_proto_rawDescGZIP() []byte {
	file_proto_Campaign_type_campaign_proto_rawDescOnce.Do(func() {
		file_proto_Campaign_type_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Campaign_type_campaign_proto_rawDesc), len(file_proto_Campaign_type_campaign_proto_rawDesc)))
	})
	return file_proto_Campaign_type_campaign_proto_rawDescData
}

var file_proto_Campaign_type_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_Campaign_type_campaign_proto_goTypes = []any{
	(*Campaign)(nil),                    // 0: campaign.Campaign
	(*ListCampaign)(nil),                // 1: campaign.ListCampaign
	(*CampaignImage)(nil),               // 2: campaign.CampaignImage
	(*CampaignReward)(nil),              // 3: campaign.CampaignReward
	(*CampaignActivity)(nil),            // 4: campaign.CampaignActivity
	(*Cattegory)(nil),                   // 5: campaign.Cattegory
	(*ListCattegory)(nil),               // 6: campaign.ListCattegory
	(*SendIDRequest)(nil),               // 7: campaign.SendIDRequest
	(*SendLimitRequest)(nil),            // 8: campaign.SendLimitRequest
	(*SendUserIDRequest)(nil),           // 9: campaign.SendUserIDRequest
	(*CreateCampaignInput)(nil),         // 10: campaign.CreateCampaignInput
	(*UpdateAttachmentInput)(nil),       // 11: campaign.UpdateAttachmentInput
	(*UpdateCampaignInput)(nil),         // 12: campaign.UpdateCampaignInput
	(*CreateCampaignImageInput)(nil),    // 13: campaign.CreateCampaignImageInput
	(*CreateCampaignRewardInput)(nil),   // 14: campaign.CreateCampaignRewardInput
	(*DeleteCampaignRewardInput)(nil),   // 15: campaign.DeleteCampaignRewardInput
	(*DeleteCampaignImageInput)(nil),    // 16: campaign.DeleteCampaignImageInput
	(*BooleanResponse)(nil),             // 17: campaign.BooleanResponse
	(*CreateCampaignActivityInput)(nil), // 18: campaign.CreateCampaignActivityInput
	(*UpdateCampaignActivityInput)(nil), // 19: campaign.UpdateCampaignActivityInput
	(*DeleteCampaignActivityInput)(nil), // 20: campaign.DeleteCampaignActivityInput
	(*GetCampaignAcitityInput)(nil),     // 21: campaign.GetCampaignAcitityInput
	(*SendCattegoryInput)(nil),          // 22: campaign.SendCattegoryInput
	(*timestamppb.Timestamp)(nil),       // 23: google.protobuf.Timestamp
}
var file_proto_Campaign_type_campaign_proto_depIdxs = []int32{
	0,  // 0: campaign.ListCampaign.data:type_name -> campaign.Campaign
	23, // 1: campaign.CampaignReward.createdAt:type_name -> google.protobuf.Timestamp
	23, // 2: campaign.CampaignReward.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: campaign.CampaignActivity.campaign:type_name -> campaign.Campaign
	23, // 4: campaign.CampaignActivity.createdAt:type_name -> google.protobuf.Timestamp
	23, // 5: campaign.CampaignActivity.updatedAt:type_name -> google.protobuf.Timestamp
	5,  // 6: campaign.ListCattegory.data:type_name -> campaign.Cattegory
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_Campaign_type_campaign_proto_init() }
func file_proto_Campaign_type_campaign_proto_init() {
	if File_proto_Campaign_type_campaign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Campaign_type_campaign_proto_rawDesc), len(file_proto_Campaign_type_campaign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_Campaign_type_campaign_proto_goTypes,
		DependencyIndexes: file_proto_Campaign_type_campaign_proto_depIdxs,
		MessageInfos:      file_proto_Campaign_type_campaign_proto_msgTypes,
	}.Build()
	File_proto_Campaign_type_campaign_proto = out.File
	file_proto_Campaign_type_campaign_proto_goTypes = nil
	file_proto_Campaign_type_campaign_proto_depIdxs = nil
}
