// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/Campaign/service.proto

package campaign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_Campaign_service_proto protoreflect.FileDescriptor

const file_proto_Campaign_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/Campaign/service.proto\x12\x04auth\x1a\"proto/Campaign/type/campaign.proto\x1a\x1bgoogle/protobuf/empty.proto2\x9b\r\n" +
	"\x0fCampaignService\x12E\n" +
	"\n" +
	"GetRewards\x12\x17.campaign.SendIDRequest\x1a\x1c.campaign.ListCampaignReward\"\x00\x12B\n" +
	"\x0eSearchCampaign\x12\x16.google.protobuf.Empty\x1a\x16.campaign.ListCampaign\"\x00\x12=\n" +
	"\x05Limit\x12\x1a.campaign.SendLimitRequest\x1a\x16.campaign.ListCampaign\"\x00\x12E\n" +
	"\fGetCampaigns\x12\x1b.campaign.SendUserIDRequest\x1a\x16.campaign.ListCampaign\"\x00\x12<\n" +
	"\vGetCampaign\x12\x17.campaign.SendIDRequest\x1a\x12.campaign.Campaign\"\x00\x12E\n" +
	"\x0eCreateCampaign\x12\x1d.campaign.CreateCampaignInput\x1a\x12.campaign.Campaign\"\x00\x12I\n" +
	"\x10UpdateAttachment\x12\x1f.campaign.UpdateAttachmentInput\x1a\x12.campaign.Campaign\"\x00\x12D\n" +
	"\x13GetUserCampaignByID\x12\x17.campaign.SendIDRequest\x1a\x12.campaign.Campaign\"\x00\x12E\n" +
	"\x0eUpdateCampaign\x12\x1d.campaign.UpdateCampaignInput\x1a\x12.campaign.Campaign\"\x00\x12J\n" +
	"\x13CreateCampaignImage\x12\x1d.campaign.CreateCampaignInput\x1a\x12.campaign.Campaign\"\x00\x12Q\n" +
	"\x14CreateCampaignReward\x12#.campaign.CreateCampaignRewardInput\x1a\x12.campaign.Campaign\"\x00\x12P\n" +
	"\fDeleteReward\x12#.campaign.DeleteCampaignRewardInput\x1a\x19.campaign.BooleanResponse\"\x00\x12N\n" +
	"\vDeleteImage\x12\".campaign.DeleteCampaignImageInput\x1a\x19.campaign.BooleanResponse\"\x00\x12U\n" +
	"\x0eCreateActivity\x12%.campaign.CreateCampaignActivityInput\x1a\x1a.campaign.CampaignActivity\"\x00\x12U\n" +
	"\x0eUpdateActivity\x12%.campaign.UpdateCampaignActivityInput\x1a\x1a.campaign.CampaignActivity\"\x00\x12U\n" +
	"\x0eDeleteActivity\x12%.campaign.DeleteCampaignActivityInput\x1a\x1a.campaign.CampaignActivity\"\x00\x12O\n" +
	"\fFindActivity\x12!.campaign.GetCampaignAcitityInput\x1a\x1a.campaign.CampaignActivity\"\x00\x12U\n" +
	"\x12FindActivityByUser\x12!.campaign.GetCampaignAcitityInput\x1a\x1a.campaign.CampaignActivity\"\x00\x12T\n" +
	"\x1bFindAllActivityByCampaignID\x12\x17.campaign.SendIDRequest\x1a\x1a.campaign.CampaignActivity\"\x00\x12F\n" +
	"\x0fCreateCattegory\x12\x1c.campaign.SendCattegoryInput\x1a\x13.campaign.Cattegory\"\x00\x12G\n" +
	"\x0fDeleteCattegory\x12\x17.campaign.SendIDRequest\x1a\x19.campaign.BooleanResponse\"\x00\x12E\n" +
	"\x10FindAllCattegory\x12\x16.google.protobuf.Empty\x1a\x17.campaign.ListCattegory\"\x00B>Z<github.com/Ilhamkawe/crowdfunding-proto/protogen/go/campaignb\x06proto3"

var file_proto_Campaign_service_proto_goTypes = []any{
	(*SendIDRequest)(nil),               // 0: campaign.SendIDRequest
	(*emptypb.Empty)(nil),               // 1: google.protobuf.Empty
	(*SendLimitRequest)(nil),            // 2: campaign.SendLimitRequest
	(*SendUserIDRequest)(nil),           // 3: campaign.SendUserIDRequest
	(*CreateCampaignInput)(nil),         // 4: campaign.CreateCampaignInput
	(*UpdateAttachmentInput)(nil),       // 5: campaign.UpdateAttachmentInput
	(*UpdateCampaignInput)(nil),         // 6: campaign.UpdateCampaignInput
	(*CreateCampaignRewardInput)(nil),   // 7: campaign.CreateCampaignRewardInput
	(*DeleteCampaignRewardInput)(nil),   // 8: campaign.DeleteCampaignRewardInput
	(*DeleteCampaignImageInput)(nil),    // 9: campaign.DeleteCampaignImageInput
	(*CreateCampaignActivityInput)(nil), // 10: campaign.CreateCampaignActivityInput
	(*UpdateCampaignActivityInput)(nil), // 11: campaign.UpdateCampaignActivityInput
	(*DeleteCampaignActivityInput)(nil), // 12: campaign.DeleteCampaignActivityInput
	(*GetCampaignAcitityInput)(nil),     // 13: campaign.GetCampaignAcitityInput
	(*SendCattegoryInput)(nil),          // 14: campaign.SendCattegoryInput
	(*ListCampaignReward)(nil),          // 15: campaign.ListCampaignReward
	(*ListCampaign)(nil),                // 16: campaign.ListCampaign
	(*Campaign)(nil),                    // 17: campaign.Campaign
	(*BooleanResponse)(nil),             // 18: campaign.BooleanResponse
	(*CampaignActivity)(nil),            // 19: campaign.CampaignActivity
	(*Cattegory)(nil),                   // 20: campaign.Cattegory
	(*ListCattegory)(nil),               // 21: campaign.ListCattegory
}
var file_proto_Campaign_service_proto_depIdxs = []int32{
	0,  // 0: auth.CampaignService.GetRewards:input_type -> campaign.SendIDRequest
	1,  // 1: auth.CampaignService.SearchCampaign:input_type -> google.protobuf.Empty
	2,  // 2: auth.CampaignService.Limit:input_type -> campaign.SendLimitRequest
	3,  // 3: auth.CampaignService.GetCampaigns:input_type -> campaign.SendUserIDRequest
	0,  // 4: auth.CampaignService.GetCampaign:input_type -> campaign.SendIDRequest
	4,  // 5: auth.CampaignService.CreateCampaign:input_type -> campaign.CreateCampaignInput
	5,  // 6: auth.CampaignService.UpdateAttachment:input_type -> campaign.UpdateAttachmentInput
	0,  // 7: auth.CampaignService.GetUserCampaignByID:input_type -> campaign.SendIDRequest
	6,  // 8: auth.CampaignService.UpdateCampaign:input_type -> campaign.UpdateCampaignInput
	4,  // 9: auth.CampaignService.CreateCampaignImage:input_type -> campaign.CreateCampaignInput
	7,  // 10: auth.CampaignService.CreateCampaignReward:input_type -> campaign.CreateCampaignRewardInput
	8,  // 11: auth.CampaignService.DeleteReward:input_type -> campaign.DeleteCampaignRewardInput
	9,  // 12: auth.CampaignService.DeleteImage:input_type -> campaign.DeleteCampaignImageInput
	10, // 13: auth.CampaignService.CreateActivity:input_type -> campaign.CreateCampaignActivityInput
	11, // 14: auth.CampaignService.UpdateActivity:input_type -> campaign.UpdateCampaignActivityInput
	12, // 15: auth.CampaignService.DeleteActivity:input_type -> campaign.DeleteCampaignActivityInput
	13, // 16: auth.CampaignService.FindActivity:input_type -> campaign.GetCampaignAcitityInput
	13, // 17: auth.CampaignService.FindActivityByUser:input_type -> campaign.GetCampaignAcitityInput
	0,  // 18: auth.CampaignService.FindAllActivityByCampaignID:input_type -> campaign.SendIDRequest
	14, // 19: auth.CampaignService.CreateCattegory:input_type -> campaign.SendCattegoryInput
	0,  // 20: auth.CampaignService.DeleteCattegory:input_type -> campaign.SendIDRequest
	1,  // 21: auth.CampaignService.FindAllCattegory:input_type -> google.protobuf.Empty
	15, // 22: auth.CampaignService.GetRewards:output_type -> campaign.ListCampaignReward
	16, // 23: auth.CampaignService.SearchCampaign:output_type -> campaign.ListCampaign
	16, // 24: auth.CampaignService.Limit:output_type -> campaign.ListCampaign
	16, // 25: auth.CampaignService.GetCampaigns:output_type -> campaign.ListCampaign
	17, // 26: auth.CampaignService.GetCampaign:output_type -> campaign.Campaign
	17, // 27: auth.CampaignService.CreateCampaign:output_type -> campaign.Campaign
	17, // 28: auth.CampaignService.UpdateAttachment:output_type -> campaign.Campaign
	17, // 29: auth.CampaignService.GetUserCampaignByID:output_type -> campaign.Campaign
	17, // 30: auth.CampaignService.UpdateCampaign:output_type -> campaign.Campaign
	17, // 31: auth.CampaignService.CreateCampaignImage:output_type -> campaign.Campaign
	17, // 32: auth.CampaignService.CreateCampaignReward:output_type -> campaign.Campaign
	18, // 33: auth.CampaignService.DeleteReward:output_type -> campaign.BooleanResponse
	18, // 34: auth.CampaignService.DeleteImage:output_type -> campaign.BooleanResponse
	19, // 35: auth.CampaignService.CreateActivity:output_type -> campaign.CampaignActivity
	19, // 36: auth.CampaignService.UpdateActivity:output_type -> campaign.CampaignActivity
	19, // 37: auth.CampaignService.DeleteActivity:output_type -> campaign.CampaignActivity
	19, // 38: auth.CampaignService.FindActivity:output_type -> campaign.CampaignActivity
	19, // 39: auth.CampaignService.FindActivityByUser:output_type -> campaign.CampaignActivity
	19, // 40: auth.CampaignService.FindAllActivityByCampaignID:output_type -> campaign.CampaignActivity
	20, // 41: auth.CampaignService.CreateCattegory:output_type -> campaign.Cattegory
	18, // 42: auth.CampaignService.DeleteCattegory:output_type -> campaign.BooleanResponse
	21, // 43: auth.CampaignService.FindAllCattegory:output_type -> campaign.ListCattegory
	22, // [22:44] is the sub-list for method output_type
	0,  // [0:22] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Campaign_service_proto_init() }
func file_proto_Campaign_service_proto_init() {
	if File_proto_Campaign_service_proto != nil {
		return
	}
	file_proto_Campaign_type_campaign_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Campaign_service_proto_rawDesc), len(file_proto_Campaign_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Campaign_service_proto_goTypes,
		DependencyIndexes: file_proto_Campaign_service_proto_depIdxs,
	}.Build()
	File_proto_Campaign_service_proto = out.File
	file_proto_Campaign_service_proto_goTypes = nil
	file_proto_Campaign_service_proto_depIdxs = nil
}
