// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/Campaign/service.proto

package campaign

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CampaignService_GetRewards_FullMethodName                  = "/auth.CampaignService/GetRewards"
	CampaignService_SearchCampaign_FullMethodName              = "/auth.CampaignService/SearchCampaign"
	CampaignService_Limit_FullMethodName                       = "/auth.CampaignService/Limit"
	CampaignService_GetCampaigns_FullMethodName                = "/auth.CampaignService/GetCampaigns"
	CampaignService_GetCampaign_FullMethodName                 = "/auth.CampaignService/GetCampaign"
	CampaignService_CreateCampaign_FullMethodName              = "/auth.CampaignService/CreateCampaign"
	CampaignService_UpdateAttachment_FullMethodName            = "/auth.CampaignService/UpdateAttachment"
	CampaignService_GetUserCampaignByID_FullMethodName         = "/auth.CampaignService/GetUserCampaignByID"
	CampaignService_UpdateCampaign_FullMethodName              = "/auth.CampaignService/UpdateCampaign"
	CampaignService_CreateCampaignImage_FullMethodName         = "/auth.CampaignService/CreateCampaignImage"
	CampaignService_CreateCampaignReward_FullMethodName        = "/auth.CampaignService/CreateCampaignReward"
	CampaignService_DeleteReward_FullMethodName                = "/auth.CampaignService/DeleteReward"
	CampaignService_DeleteImage_FullMethodName                 = "/auth.CampaignService/DeleteImage"
	CampaignService_CreateActivity_FullMethodName              = "/auth.CampaignService/CreateActivity"
	CampaignService_UpdateActivity_FullMethodName              = "/auth.CampaignService/UpdateActivity"
	CampaignService_DeleteActivity_FullMethodName              = "/auth.CampaignService/DeleteActivity"
	CampaignService_FindActivity_FullMethodName                = "/auth.CampaignService/FindActivity"
	CampaignService_FindActivityByUser_FullMethodName          = "/auth.CampaignService/FindActivityByUser"
	CampaignService_FindAllActivityByCampaignID_FullMethodName = "/auth.CampaignService/FindAllActivityByCampaignID"
	CampaignService_CreateCattegory_FullMethodName             = "/auth.CampaignService/CreateCattegory"
	CampaignService_DeleteCattegory_FullMethodName             = "/auth.CampaignService/DeleteCattegory"
	CampaignService_FindAllCattegory_FullMethodName            = "/auth.CampaignService/FindAllCattegory"
)

// CampaignServiceClient is the client API for CampaignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignServiceClient interface {
	GetRewards(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*ListCampaignReward, error)
	SearchCampaign(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCampaign, error)
	Limit(ctx context.Context, in *SendLimitRequest, opts ...grpc.CallOption) (*ListCampaign, error)
	GetCampaigns(ctx context.Context, in *SendUserIDRequest, opts ...grpc.CallOption) (*ListCampaign, error)
	GetCampaign(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*Campaign, error)
	CreateCampaign(ctx context.Context, in *CreateCampaignInput, opts ...grpc.CallOption) (*Campaign, error)
	UpdateAttachment(ctx context.Context, in *UpdateAttachmentInput, opts ...grpc.CallOption) (*Campaign, error)
	GetUserCampaignByID(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*Campaign, error)
	UpdateCampaign(ctx context.Context, in *UpdateCampaignInput, opts ...grpc.CallOption) (*Campaign, error)
	CreateCampaignImage(ctx context.Context, in *CreateCampaignInput, opts ...grpc.CallOption) (*Campaign, error)
	CreateCampaignReward(ctx context.Context, in *CreateCampaignRewardInput, opts ...grpc.CallOption) (*Campaign, error)
	DeleteReward(ctx context.Context, in *DeleteCampaignRewardInput, opts ...grpc.CallOption) (*BooleanResponse, error)
	DeleteImage(ctx context.Context, in *DeleteCampaignImageInput, opts ...grpc.CallOption) (*BooleanResponse, error)
	CreateActivity(ctx context.Context, in *CreateCampaignActivityInput, opts ...grpc.CallOption) (*CampaignActivity, error)
	UpdateActivity(ctx context.Context, in *UpdateCampaignActivityInput, opts ...grpc.CallOption) (*CampaignActivity, error)
	DeleteActivity(ctx context.Context, in *DeleteCampaignActivityInput, opts ...grpc.CallOption) (*CampaignActivity, error)
	FindActivity(ctx context.Context, in *GetCampaignAcitityInput, opts ...grpc.CallOption) (*CampaignActivity, error)
	FindActivityByUser(ctx context.Context, in *GetCampaignAcitityInput, opts ...grpc.CallOption) (*CampaignActivity, error)
	FindAllActivityByCampaignID(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*CampaignActivity, error)
	CreateCattegory(ctx context.Context, in *SendCattegoryInput, opts ...grpc.CallOption) (*Cattegory, error)
	DeleteCattegory(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*BooleanResponse, error)
	FindAllCattegory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCattegory, error)
}

type campaignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignServiceClient(cc grpc.ClientConnInterface) CampaignServiceClient {
	return &campaignServiceClient{cc}
}

func (c *campaignServiceClient) GetRewards(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*ListCampaignReward, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignReward)
	err := c.cc.Invoke(ctx, CampaignService_GetRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) SearchCampaign(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCampaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaign)
	err := c.cc.Invoke(ctx, CampaignService_SearchCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) Limit(ctx context.Context, in *SendLimitRequest, opts ...grpc.CallOption) (*ListCampaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaign)
	err := c.cc.Invoke(ctx, CampaignService_Limit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetCampaigns(ctx context.Context, in *SendUserIDRequest, opts ...grpc.CallOption) (*ListCampaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaign)
	err := c.cc.Invoke(ctx, CampaignService_GetCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetCampaign(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CreateCampaign(ctx context.Context, in *CreateCampaignInput, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) UpdateAttachment(ctx context.Context, in *UpdateAttachmentInput, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_UpdateAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetUserCampaignByID(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_GetUserCampaignByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) UpdateCampaign(ctx context.Context, in *UpdateCampaignInput, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_UpdateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CreateCampaignImage(ctx context.Context, in *CreateCampaignInput, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_CreateCampaignImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CreateCampaignReward(ctx context.Context, in *CreateCampaignRewardInput, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_CreateCampaignReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) DeleteReward(ctx context.Context, in *DeleteCampaignRewardInput, opts ...grpc.CallOption) (*BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooleanResponse)
	err := c.cc.Invoke(ctx, CampaignService_DeleteReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) DeleteImage(ctx context.Context, in *DeleteCampaignImageInput, opts ...grpc.CallOption) (*BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooleanResponse)
	err := c.cc.Invoke(ctx, CampaignService_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CreateActivity(ctx context.Context, in *CreateCampaignActivityInput, opts ...grpc.CallOption) (*CampaignActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignActivity)
	err := c.cc.Invoke(ctx, CampaignService_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) UpdateActivity(ctx context.Context, in *UpdateCampaignActivityInput, opts ...grpc.CallOption) (*CampaignActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignActivity)
	err := c.cc.Invoke(ctx, CampaignService_UpdateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) DeleteActivity(ctx context.Context, in *DeleteCampaignActivityInput, opts ...grpc.CallOption) (*CampaignActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignActivity)
	err := c.cc.Invoke(ctx, CampaignService_DeleteActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) FindActivity(ctx context.Context, in *GetCampaignAcitityInput, opts ...grpc.CallOption) (*CampaignActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignActivity)
	err := c.cc.Invoke(ctx, CampaignService_FindActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) FindActivityByUser(ctx context.Context, in *GetCampaignAcitityInput, opts ...grpc.CallOption) (*CampaignActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignActivity)
	err := c.cc.Invoke(ctx, CampaignService_FindActivityByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) FindAllActivityByCampaignID(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*CampaignActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignActivity)
	err := c.cc.Invoke(ctx, CampaignService_FindAllActivityByCampaignID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CreateCattegory(ctx context.Context, in *SendCattegoryInput, opts ...grpc.CallOption) (*Cattegory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cattegory)
	err := c.cc.Invoke(ctx, CampaignService_CreateCattegory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) DeleteCattegory(ctx context.Context, in *SendIDRequest, opts ...grpc.CallOption) (*BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooleanResponse)
	err := c.cc.Invoke(ctx, CampaignService_DeleteCattegory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) FindAllCattegory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCattegory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCattegory)
	err := c.cc.Invoke(ctx, CampaignService_FindAllCattegory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignServiceServer is the server API for CampaignService service.
// All implementations should embed UnimplementedCampaignServiceServer
// for forward compatibility.
type CampaignServiceServer interface {
	GetRewards(context.Context, *SendIDRequest) (*ListCampaignReward, error)
	SearchCampaign(context.Context, *emptypb.Empty) (*ListCampaign, error)
	Limit(context.Context, *SendLimitRequest) (*ListCampaign, error)
	GetCampaigns(context.Context, *SendUserIDRequest) (*ListCampaign, error)
	GetCampaign(context.Context, *SendIDRequest) (*Campaign, error)
	CreateCampaign(context.Context, *CreateCampaignInput) (*Campaign, error)
	UpdateAttachment(context.Context, *UpdateAttachmentInput) (*Campaign, error)
	GetUserCampaignByID(context.Context, *SendIDRequest) (*Campaign, error)
	UpdateCampaign(context.Context, *UpdateCampaignInput) (*Campaign, error)
	CreateCampaignImage(context.Context, *CreateCampaignInput) (*Campaign, error)
	CreateCampaignReward(context.Context, *CreateCampaignRewardInput) (*Campaign, error)
	DeleteReward(context.Context, *DeleteCampaignRewardInput) (*BooleanResponse, error)
	DeleteImage(context.Context, *DeleteCampaignImageInput) (*BooleanResponse, error)
	CreateActivity(context.Context, *CreateCampaignActivityInput) (*CampaignActivity, error)
	UpdateActivity(context.Context, *UpdateCampaignActivityInput) (*CampaignActivity, error)
	DeleteActivity(context.Context, *DeleteCampaignActivityInput) (*CampaignActivity, error)
	FindActivity(context.Context, *GetCampaignAcitityInput) (*CampaignActivity, error)
	FindActivityByUser(context.Context, *GetCampaignAcitityInput) (*CampaignActivity, error)
	FindAllActivityByCampaignID(context.Context, *SendIDRequest) (*CampaignActivity, error)
	CreateCattegory(context.Context, *SendCattegoryInput) (*Cattegory, error)
	DeleteCattegory(context.Context, *SendIDRequest) (*BooleanResponse, error)
	FindAllCattegory(context.Context, *emptypb.Empty) (*ListCattegory, error)
}

// UnimplementedCampaignServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignServiceServer struct{}

func (UnimplementedCampaignServiceServer) GetRewards(context.Context, *SendIDRequest) (*ListCampaignReward, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewards not implemented")
}
func (UnimplementedCampaignServiceServer) SearchCampaign(context.Context, *emptypb.Empty) (*ListCampaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) Limit(context.Context, *SendLimitRequest) (*ListCampaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Limit not implemented")
}
func (UnimplementedCampaignServiceServer) GetCampaigns(context.Context, *SendUserIDRequest) (*ListCampaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaigns not implemented")
}
func (UnimplementedCampaignServiceServer) GetCampaign(context.Context, *SendIDRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) CreateCampaign(context.Context, *CreateCampaignInput) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) UpdateAttachment(context.Context, *UpdateAttachmentInput) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttachment not implemented")
}
func (UnimplementedCampaignServiceServer) GetUserCampaignByID(context.Context, *SendIDRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCampaignByID not implemented")
}
func (UnimplementedCampaignServiceServer) UpdateCampaign(context.Context, *UpdateCampaignInput) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) CreateCampaignImage(context.Context, *CreateCampaignInput) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaignImage not implemented")
}
func (UnimplementedCampaignServiceServer) CreateCampaignReward(context.Context, *CreateCampaignRewardInput) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaignReward not implemented")
}
func (UnimplementedCampaignServiceServer) DeleteReward(context.Context, *DeleteCampaignRewardInput) (*BooleanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReward not implemented")
}
func (UnimplementedCampaignServiceServer) DeleteImage(context.Context, *DeleteCampaignImageInput) (*BooleanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedCampaignServiceServer) CreateActivity(context.Context, *CreateCampaignActivityInput) (*CampaignActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedCampaignServiceServer) UpdateActivity(context.Context, *UpdateCampaignActivityInput) (*CampaignActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (UnimplementedCampaignServiceServer) DeleteActivity(context.Context, *DeleteCampaignActivityInput) (*CampaignActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteActivity not implemented")
}
func (UnimplementedCampaignServiceServer) FindActivity(context.Context, *GetCampaignAcitityInput) (*CampaignActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindActivity not implemented")
}
func (UnimplementedCampaignServiceServer) FindActivityByUser(context.Context, *GetCampaignAcitityInput) (*CampaignActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindActivityByUser not implemented")
}
func (UnimplementedCampaignServiceServer) FindAllActivityByCampaignID(context.Context, *SendIDRequest) (*CampaignActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllActivityByCampaignID not implemented")
}
func (UnimplementedCampaignServiceServer) CreateCattegory(context.Context, *SendCattegoryInput) (*Cattegory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCattegory not implemented")
}
func (UnimplementedCampaignServiceServer) DeleteCattegory(context.Context, *SendIDRequest) (*BooleanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCattegory not implemented")
}
func (UnimplementedCampaignServiceServer) FindAllCattegory(context.Context, *emptypb.Empty) (*ListCattegory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllCattegory not implemented")
}
func (UnimplementedCampaignServiceServer) testEmbeddedByValue() {}

// UnsafeCampaignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignServiceServer will
// result in compilation errors.
type UnsafeCampaignServiceServer interface {
	mustEmbedUnimplementedCampaignServiceServer()
}

func RegisterCampaignServiceServer(s grpc.ServiceRegistrar, srv CampaignServiceServer) {
	// If the following call pancis, it indicates UnimplementedCampaignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CampaignService_ServiceDesc, srv)
}

func _CampaignService_GetRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetRewards(ctx, req.(*SendIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_SearchCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).SearchCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_SearchCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).SearchCampaign(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_Limit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).Limit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_Limit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).Limit(ctx, req.(*SendLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_GetCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetCampaigns(ctx, req.(*SendUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetCampaign(ctx, req.(*SendIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, req.(*CreateCampaignInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_UpdateAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttachmentInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).UpdateAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_UpdateAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).UpdateAttachment(ctx, req.(*UpdateAttachmentInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_GetUserCampaignByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetUserCampaignByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetUserCampaignByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetUserCampaignByID(ctx, req.(*SendIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_UpdateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).UpdateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_UpdateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).UpdateCampaign(ctx, req.(*UpdateCampaignInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CreateCampaignImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCampaignImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CreateCampaignImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCampaignImage(ctx, req.(*CreateCampaignInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CreateCampaignReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRewardInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCampaignReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CreateCampaignReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCampaignReward(ctx, req.(*CreateCampaignRewardInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_DeleteReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRewardInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).DeleteReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_DeleteReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).DeleteReward(ctx, req.(*DeleteCampaignRewardInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignImageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).DeleteImage(ctx, req.(*DeleteCampaignImageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignActivityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateActivity(ctx, req.(*CreateCampaignActivityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignActivityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_UpdateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).UpdateActivity(ctx, req.(*UpdateCampaignActivityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_DeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignActivityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).DeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_DeleteActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).DeleteActivity(ctx, req.(*DeleteCampaignActivityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_FindActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignAcitityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).FindActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_FindActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).FindActivity(ctx, req.(*GetCampaignAcitityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_FindActivityByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignAcitityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).FindActivityByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_FindActivityByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).FindActivityByUser(ctx, req.(*GetCampaignAcitityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_FindAllActivityByCampaignID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).FindAllActivityByCampaignID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_FindAllActivityByCampaignID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).FindAllActivityByCampaignID(ctx, req.(*SendIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CreateCattegory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCattegoryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCattegory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CreateCattegory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCattegory(ctx, req.(*SendCattegoryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_DeleteCattegory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).DeleteCattegory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_DeleteCattegory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).DeleteCattegory(ctx, req.(*SendIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_FindAllCattegory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).FindAllCattegory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_FindAllCattegory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).FindAllCattegory(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignService_ServiceDesc is the grpc.ServiceDesc for CampaignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.CampaignService",
	HandlerType: (*CampaignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRewards",
			Handler:    _CampaignService_GetRewards_Handler,
		},
		{
			MethodName: "SearchCampaign",
			Handler:    _CampaignService_SearchCampaign_Handler,
		},
		{
			MethodName: "Limit",
			Handler:    _CampaignService_Limit_Handler,
		},
		{
			MethodName: "GetCampaigns",
			Handler:    _CampaignService_GetCampaigns_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _CampaignService_GetCampaign_Handler,
		},
		{
			MethodName: "CreateCampaign",
			Handler:    _CampaignService_CreateCampaign_Handler,
		},
		{
			MethodName: "UpdateAttachment",
			Handler:    _CampaignService_UpdateAttachment_Handler,
		},
		{
			MethodName: "GetUserCampaignByID",
			Handler:    _CampaignService_GetUserCampaignByID_Handler,
		},
		{
			MethodName: "UpdateCampaign",
			Handler:    _CampaignService_UpdateCampaign_Handler,
		},
		{
			MethodName: "CreateCampaignImage",
			Handler:    _CampaignService_CreateCampaignImage_Handler,
		},
		{
			MethodName: "CreateCampaignReward",
			Handler:    _CampaignService_CreateCampaignReward_Handler,
		},
		{
			MethodName: "DeleteReward",
			Handler:    _CampaignService_DeleteReward_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _CampaignService_DeleteImage_Handler,
		},
		{
			MethodName: "CreateActivity",
			Handler:    _CampaignService_CreateActivity_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _CampaignService_UpdateActivity_Handler,
		},
		{
			MethodName: "DeleteActivity",
			Handler:    _CampaignService_DeleteActivity_Handler,
		},
		{
			MethodName: "FindActivity",
			Handler:    _CampaignService_FindActivity_Handler,
		},
		{
			MethodName: "FindActivityByUser",
			Handler:    _CampaignService_FindActivityByUser_Handler,
		},
		{
			MethodName: "FindAllActivityByCampaignID",
			Handler:    _CampaignService_FindAllActivityByCampaignID_Handler,
		},
		{
			MethodName: "CreateCattegory",
			Handler:    _CampaignService_CreateCattegory_Handler,
		},
		{
			MethodName: "DeleteCattegory",
			Handler:    _CampaignService_DeleteCattegory_Handler,
		},
		{
			MethodName: "FindAllCattegory",
			Handler:    _CampaignService_FindAllCattegory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Campaign/service.proto",
}
