syntax = "proto3";

package campaign;

option go_package = "github.com/Ilhamkawe/crowdfunding-proto/protogen/go/campaign";
import "google/protobuf/timestamp.proto";

message Campaign {
  int64 id = 1;
  int64 userId = 2;
  string name = 3;
  string shortDescription = 4;
  string description = 5;
  int64 backerCount = 6;
  int64 goalAmount = 7;
  string cattegory = 8;
  int64 currentAmount = 9;
  string slug = 10;
  string status = 11;
  string Attachment = 12;
  bool collectAble = 13;
  string finishAt = 15;
  string createdAt = 16;
  string updatedAt = 17;
}

message ListCampaign {
  repeated Campaign data = 1;
}

message CampaignImage {
  int64 id = 1;
  int64 campaignID = 2;
  string fileName = 3;
  int32 isPrimary = 4;
  string createdAt = 16;
  string updatedAt = 17;
}

message CampaignReward {
  int32 id = 1;
  int32 campaignId = 2;
  string description = 3;
  string perks = 4;
  int32 minDonate = 5;
  google.protobuf.Timestamp createdAt = 6;
  google.protobuf.Timestamp updatedAt = 7;
}

message ListCampaignReward{
  repeated CampaignReward data = 1;
}

message CampaignActivity {
  int32 id = 1;
  int32 campaignId = 2;
  string name = 3;
  string shortDescription = 4;
  string description = 5;
  string imageUrl = 6;
  string slug = 7;
  Campaign campaign = 8;
  google.protobuf.Timestamp createdAt = 9;
  google.protobuf.Timestamp updatedAt = 10;
}

message ListCampaignActivity {
  repeated CampaignActivity data = 1;
}

message Cattegory {
  int32 id = 1;
  string name = 2;
}

message ListCattegory {
  repeated Cattegory data = 1;
}

message SendIDRequest {
  int32 id = 1;
}

message SendLimitRequest {
  int32 limit = 1;
}

message SendUserIDRequest {
  int32 userId = 1;
}

message CreateCampaignInput {
  string Name = 1;
  string ShortDescription = 2;
  string Description = 3;
  string GoalAmount = 4;
  string Cattegory = 5;
  string FinishAt = 6;
  string Path = 7;
  int32 UserId = 8;
}

message UpdateAttachmentInput {
  string CampaignID = 1;
  string Action = 2;
  string Path = 3;
  int32 UserId = 4;
}

message UpdateCampaignInput{
  int32 Id = 1;
  string Name = 2;
  string ShortDescription = 3;
  string Description = 4;
  string GoalAmount = 5;
  string Cattegory = 6;
  string UserId = 7;
}

message CreateCampaignImageInput{
  int32 CampaignId = 1;
  bool IsPrimary = 2;
  int32 UserId = 3;
  bytes chunk = 4;
}

message CreateCampaignRewardInput{
  int32 CampaignId = 1;
  string Description = 2;
  string Perks = 3;
  string MinDonate = 4;
  string UserId = 5;
}

message DeleteCampaignRewardInput{
  int32 CampaignId = 1;
  int32 RewardId = 2;
  string UserId = 3;
}

message DeleteCampaignImageInput{
  int32 CampaignId = 1;
  int32 ImageId = 2;
  string UserId = 3;
}

message BooleanResponse{
  string message = 1;
  bool success = 2;
}

message CreateCampaignActivityInput{
  int32 CampaignId = 1;
  string Name = 2;
  string ShortDescription = 3;
  string Description = 4;
  string ImageUrl = 5;
  bytes chunk = 6;
  string UserId = 7;
}

message UpdateCampaignActivityInput{
  int32 Id = 1;
  int32 CampaignId = 2;
  string Name = 3;
  string ShortDescription = 4;
  string Description = 5;
  string ImageUrl = 6;
  bytes chunk = 7;
  string UserId = 8;
}

message DeleteCampaignActivityInput{
  int32 CampaignId = 1;
  int32 ActivityId = 2;
  string UserId = 3;
}

message GetCampaignAcitityInput{
  int32 Id = 1;
  int32 CampaignId = 2;
}

message SendCattegoryInput{
  string Name = 1;
}

